### Create new report 
POST http://localhost:3000/reports
Content-Type: application/json

{
  "price": 20000,
  "brand": "Chevrolet",
  "model": "Montana",
  "year": 2008,
  "mileage": 500,
  "longitude": "45",
  "latitude": "45"
}

### Approve an existing Report
PATCH  http://localhost:3000/reports/4
Content-Type: application/json

{
  "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?brand=Chevrolet&model=Montana&year=2008&mileage=7000&latitude=45&longitude=45