### Create a New User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "teste7@mail.com",
  "password": "123456789"
}


### Sign-in a registered user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "teste7@mail.com",
  "password": "123456789"
}

### Sign-out the user on current session
POST  http://localhost:3000/auth/signout

### Get the signed-in user on current session
GET http://localhost:3000/auth/signeduser

### Find a particular user by param id
GET http://localhost:3000/auth/2

### Find All Users given email by query string
GET http://localhost:3000/auth?email=daniel@mail.com

### Find All Users 
GET http://localhost:3000/auth

### Remove particular user by given id
DELETE http://localhost:3000/auth/3

### Update particular user by given id
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "password": "dabuek123"
}

### Set a color
GET http://localhost:3000/auth/colors/blue

### Get the color
GET http://localhost:3000/auth/colors
